"""
Autoresearch image restoration training script. Single-GPU, single-file.
Usage: uv run train.py

Reads clean images via WebDataset, applies a degradation pipeline on-the-fly
(from params.json), and trains a restoration model to recover clean images.
"""

import os
os.environ["PYTORCH_ALLOC_CONF"] = "expandable_segments:True"

import gc
import json
import math
import time

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from PIL import Image

from prepare import load_degradation_params, make_dataloader_restoration, scandir
from x_distortion import add_distortion

# ---------------------------------------------------------------------------
# Hyperparameters (edit these directly — the agent modifies this section)
# ---------------------------------------------------------------------------

# Data
PARAMS_PATH = ".claude/skills/image-degradation-simulator-workspace/iteration-3/eval-16/with_skill/outputs/params.json"
TRAIN_SHARDS = "datasets/DIV2K/DIV2K_train_HR_wds/train-*.tar"
VAL_DIR = "datasets/DIV2K/DIV2K_valid_HR"
VAL_CROP_SIZE = 256          # center-crop size for validation images
VAL_COUNT = 100              # number of val images to use (≤ total available)

# Validation uses the TRUE degradation (ground truth that produced the target image),
# NOT the skill's predicted pipeline. If the target was generated by us, we know the
# exact params. If unknown, set to the same as PARAMS_PATH and treat val metrics as
# an upper bound (model can't beat the skill's estimation error).
VAL_PARAMS_PATH = PARAMS_PATH  # replace with ground-truth params if available

# Training
TIME_BUDGET = 300            # training wall-clock budget in seconds
BATCH_SIZE = 16
NUM_WORKERS = 4
SHUFFLE_BUFFER = 1000

# Optimization
LEARNING_RATE = 1e-3
WEIGHT_DECAY = 1e-4
ADAM_BETAS = (0.9, 0.999)
WARMUP_STEPS = 100
LR_SCHEDULE = "cosine"       # "cosine" or "constant"

# Logging
LOG_INTERVAL = 25            # steps between PSNR logging
VAL_INTERVAL = 200           # steps between full validation

# ---------------------------------------------------------------------------
# Validation dataset
# ---------------------------------------------------------------------------

class ValDataset:
    """Load validation images from disk, center-crop, apply degradation.

    Returns (degraded, clean) float32 tensors in [0, 1], shape [3, H, W].
    """

    def __init__(self, val_dir, crop_size=256, count=None, params_path=None):
        self.img_paths = sorted(scandir(val_dir, full_path=True))
        if count:
            self.img_paths = self.img_paths[:count]
        self.crop_size = crop_size
        self.pipeline = load_degradation_params(params_path) if params_path else []

    def __len__(self):
        return len(self.img_paths)

    def __getitem__(self, idx):
        img = np.array(Image.open(self.img_paths[idx]).convert("RGB"), dtype=np.uint8)
        h, w = img.shape[:2]
        # Center crop
        top = max(0, (h - self.crop_size) // 2)
        left = max(0, (w - self.crop_size) // 2)
        img = img[top:top + self.crop_size, left:left + self.crop_size]

        clean = img.copy()
        for func_name, severity in self.pipeline:
            img = add_distortion(img, severity=severity, distortion_name=func_name)

        degraded_t = torch.from_numpy(img).permute(2, 0, 1).float() / 255.0
        clean_t = torch.from_numpy(clean).permute(2, 0, 1).float() / 255.0
        return degraded_t, clean_t


@torch.no_grad()
def evaluate(model, val_loader, device, autocast_ctx):
    """Compute average PSNR over validation set."""
    model.eval()
    psnr_sum = 0.0
    count = 0
    for degraded, clean in val_loader:
        degraded = degraded.to(device)
        clean = clean.to(device)
        with autocast_ctx:
            pred = model(degraded)
        psnr_sum += compute_psnr(pred.float(), clean)
        count += 1
    model.train()
    return psnr_sum / count if count else 0.0


# ---------------------------------------------------------------------------
# Metrics
# ---------------------------------------------------------------------------

def compute_psnr(pred, target):
    """PSNR in dB. Assumes pixel values in [0, 1]."""
    mse = F.mse_loss(pred, target)
    if mse == 0:
        return 100.0
    return 20 * math.log10(1.0) - 10 * math.log10(mse.item())


# ---------------------------------------------------------------------------
# Model (replace this class with your own architecture)
# ---------------------------------------------------------------------------

class RestoreNet(nn.Module):
    """Baseline restoration model placeholder. Replace with your architecture."""

    def __init__(self, in_ch=3, out_ch=3):
        super().__init__()
        # ------------------------------------------------------------------
        # TODO: define your model layers here
        # ------------------------------------------------------------------
        self.model = nn.Sequential(
            nn.Conv2d(in_ch, 32, 3, padding=1),
            nn.ReLU(inplace=True),
            nn.Conv2d(32, out_ch, 3, padding=1),
        )

    def forward(self, x):
        return self.model(x) + x  # residual by default


# ---------------------------------------------------------------------------
# Setup
# ---------------------------------------------------------------------------

t_start = time.time()
torch.manual_seed(42)
torch.cuda.manual_seed(42)
torch.set_float32_matmul_precision("high")
device = torch.device("cuda")
autocast_ctx = torch.amp.autocast(device_type="cuda", dtype=torch.bfloat16)

print(f"Device: {torch.cuda.get_device_name(device)}")
print(f"Params: {PARAMS_PATH}")
print(f"Train shards: {TRAIN_SHARDS}")
print(f"Val dir: {VAL_DIR} ({VAL_COUNT} images)")

# Build validation dataloader
val_dataset = ValDataset(VAL_DIR, crop_size=VAL_CROP_SIZE, count=VAL_COUNT, params_path=VAL_PARAMS_PATH)
val_loader = torch.utils.data.DataLoader(val_dataset, batch_size=BATCH_SIZE,
                                          shuffle=False, num_workers=NUM_WORKERS,
                                          pin_memory=True)
# Pre-load one val batch to check
val_x, val_y = next(iter(val_loader))
print(f"Val: {len(val_dataset)} samples, x {tuple(val_x.shape)}, y {tuple(val_y.shape)}")

# Model
model = RestoreNet(in_ch=3, out_ch=3)
model.to(device)
num_params = sum(p.numel() for p in model.parameters())
print(f"Model params: {num_params:,}")

model = torch.compile(model, dynamic=False)

# Optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=LEARNING_RATE,
                               betas=ADAM_BETAS, weight_decay=WEIGHT_DECAY)

# Training dataloader
train_loader = make_dataloader_restoration(
    params_path=PARAMS_PATH,
    shards_url=TRAIN_SHARDS,
    batch_size=BATCH_SIZE,
    num_workers=NUM_WORKERS,
    shuffle_buffer=SHUFFLE_BUFFER,
)
x, y, epoch = next(train_loader)
x, y = x.to(device), y.to(device)

print(f"Train: x {tuple(x.shape)} [{x.min():.3f},{x.max():.3f}], "
      f"y {tuple(y.shape)} [{y.min():.3f},{y.max():.3f}]")
print(f"Time budget: {TIME_BUDGET}s  Batch: {BATCH_SIZE}  LR: {LEARNING_RATE}")

# ---------------------------------------------------------------------------
# LR schedule
# ---------------------------------------------------------------------------

def get_lr_multiplier(step, total_steps):
    if step < WARMUP_STEPS:
        return step / max(1, WARMUP_STEPS)
    if LR_SCHEDULE == "cosine":
        progress = (step - WARMUP_STEPS) / max(1, total_steps - WARMUP_STEPS)
        return 0.5 * (1 + math.cos(math.pi * progress))
    return 1.0

# ---------------------------------------------------------------------------
# Training loop
# ---------------------------------------------------------------------------

t_start_training = time.time()
smooth_loss = 0
total_training_time = 0
step = 0
best_psnr = 0
best_val_psnr = 0

while True:
    torch.cuda.synchronize()
    t0 = time.time()

    # Forward + backward
    with autocast_ctx:
        pred = model(x)
        loss = F.l1_loss(pred, y)

    loss.backward()

    # LR update
    lrm = get_lr_multiplier(step, max(step + 1, 1000))
    for group in optimizer.param_groups:
        group["lr"] = LEARNING_RATE * lrm

    optimizer.step()
    optimizer.zero_grad(set_to_none=True)

    # Fetch next batch
    x, y, epoch = next(train_loader)
    x, y = x.to(device, non_blocking=True), y.to(device, non_blocking=True)

    torch.cuda.synchronize()
    t1 = time.time()
    dt = t1 - t0

    # Skip warmup steps for timing
    if step > 5:
        total_training_time += dt

    # Logging
    loss_f = loss.item()
    ema_beta = 0.95
    smooth_loss = ema_beta * smooth_loss + (1 - ema_beta) * loss_f
    debiased_loss = smooth_loss / (1 - ema_beta ** (step + 1))

    if step % LOG_INTERVAL == 0:
        with torch.no_grad(), autocast_ctx:
            train_psnr = compute_psnr(pred.float(), y)
            best_psnr = max(best_psnr, train_psnr)

    if step > 0 and step % VAL_INTERVAL == 0:
        val_psnr = evaluate(model, val_loader, device, autocast_ctx)
        best_val_psnr = max(best_val_psnr, val_psnr)
        print(f"\n  [Val @ step {step}] PSNR: {val_psnr:.2f} dB  (best: {best_val_psnr:.2f})")

    progress = min(total_training_time / TIME_BUDGET, 1.0)
    pct = 100 * progress
    remaining = max(0, TIME_BUDGET - total_training_time)
    imgs_per_sec = int(BATCH_SIZE / dt) if dt > 0 else 0

    print(f"\rstep {step:05d} ({pct:.1f}%) | loss: {debiased_loss:.6f} | lr: {LEARNING_RATE * lrm:.2e} | "
          f"psnr: {best_psnr:.2f}dB | dt: {dt*1000:.0f}ms | imgs/s: {imgs_per_sec} | "
          f"epoch: {epoch} | rem: {remaining:.0f}s    ", end="", flush=True)

    # GC management
    if step == 0:
        gc.collect()
        gc.freeze()
        gc.disable()
    elif (step + 1) % 5000 == 0:
        gc.collect()

    step += 1

    if step > 10 and total_training_time >= TIME_BUDGET:
        break

print()

# ---------------------------------------------------------------------------
# Final evaluation
# ---------------------------------------------------------------------------

print("Running final validation...")
val_psnr = evaluate(model, val_loader, device, autocast_ctx)
total_imgs = step * BATCH_SIZE

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------

t_end = time.time()
peak_vram_mb = torch.cuda.max_memory_allocated() / 1024 / 1024
print("---")
print(f"val_psnr_db:       {val_psnr:.2f}")
print(f"best_train_psnr:   {best_psnr:.2f}")
print(f"best_val_psnr:     {best_val_psnr:.2f}")
print(f"final_loss:        {loss.item():.6f}")
print(f"training_seconds:  {total_training_time:.1f}")
print(f"total_seconds:     {t_end - t_start:.1f}")
print(f"peak_vram_mb:      {peak_vram_mb:.1f}")
print(f"num_steps:         {step}")
print(f"num_params_M:      {num_params / 1e6:.1f}")
print(f"total_imgs:        {total_imgs}")
print(f"batch_size:        {BATCH_SIZE}")
print(f"learning_rate:     {LEARNING_RATE}")
