"""
Autoresearch image restoration training script. Single-GPU, single-file.
Usage: uv run train.py

Reads clean images via WebDataset, applies a degradation pipeline on-the-fly
(from params.json), and trains a restoration model to recover clean images.
"""

import os
os.environ["PYTORCH_ALLOC_CONF"] = "expandable_segments:True"

import gc
import json
import math
import time

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from PIL import Image

from prepare import load_degradation_params, make_dataloader_restoration, scandir
from x_distortion import add_distortion

# ---------------------------------------------------------------------------
# Hyperparameters (edit these directly — the agent modifies this section)
# ---------------------------------------------------------------------------

# Data
# Training degradation:
#   None = random pipeline per sample (blind restoration baseline)
#   "path/to/params.json" = fixed degradation from skill output (targeted)
PARAMS_PATH = None
TRAIN_SHARDS = "datasets/DIV2K/DIV2K_train_HR_wds/train-*.tar"

# Validation: standard SR benchmarks + DIV2K valid. Uses HR/original clean images
# degraded with VAL_PARAMS_PATH (ground-truth degradation, NOT skill prediction).
VAL_DIRS = [
    "datasets/Set5/GTmod4",
    "datasets/Set14/GTmod4",
    "datasets/B100/GTmod4",
    "datasets/Urban100/GTmod4",
    "datasets/Manga109/GTmod4",
    "datasets/DIV2K/DIV2K_valid_HR",
]
VAL_COUNT = 0                # max images per val set (0 = use all)

# Validation uses the TRUE degradation (ground truth that produced the target image),
# NOT the skill's predicted pipeline. If the target was generated by us, we know the
# exact params. If unknown, set to the same as PARAMS_PATH and treat val metrics as
# an upper bound (model can't beat the skill's estimation error).
VAL_PARAMS_PATH = PARAMS_PATH  # replace with ground-truth params if available

# Model architecture (SwinIR)
EMBED_DIM = 64
DEPTHS = (2, 2, 2, 2)       # Swin blocks per RSTB stage
NUM_HEADS = (4, 4, 4, 4)     # attention heads per stage
WINDOW_SIZE = 8
MLP_RATIO = 2

# Training
EPOCH_BUDGET = 1              # epochs to train (0 = use TIME_BUDGET fallback)
TIME_BUDGET = 600             # fallback: training wall-clock budget in seconds
CHECKPOINT_INTERVAL = 4       # save/validate N times per epoch
BATCH_SIZE = 16
NUM_WORKERS = 4
SHUFFLE_BUFFER = 1000

# Optimization
LEARNING_RATE = 1e-3
WEIGHT_DECAY = 1e-4
ADAM_BETAS = (0.9, 0.999)
WARMUP_STEPS = 100
LR_SCHEDULE = "cosine"       # "cosine" or "constant"

# Loss function: "l1", "mse", "huber", "l1+mse", "l1+fft", "l1+edge"
LOSS_FN = "l1"
HUBER_DELTA = 0.1
GRAD_CLIP = 0.0              # 0 = no gradient clipping
AMP_DTYPE = "bfloat16"       # autocast dtype: "bfloat16" or "float32"
LOSS_WEIGHTS = (1.0, 0.1)    # (primary, auxiliary) weight for combined losses

# Logging
LOG_INTERVAL = 25            # steps between PSNR logging

# Environment variable overrides for parallel experiments
for _v in ("PARAMS_PATH", "VAL_PARAMS_PATH", "EMBED_DIM", "BATCH_SIZE", "LEARNING_RATE",
           "WEIGHT_DECAY", "WARMUP_STEPS", "TIME_BUDGET", "EPOCH_BUDGET",
           "CHECKPOINT_INTERVAL", "WINDOW_SIZE", "MLP_RATIO",
           "LOG_INTERVAL", "NUM_WORKERS", "SHUFFLE_BUFFER",
           "LR_SCHEDULE", "VAL_COUNT", "DEPTHS", "NUM_HEADS", "ADAM_BETAS",
           "LOSS_FN", "HUBER_DELTA", "GRAD_CLIP", "LOSS_WEIGHTS", "AMP_DTYPE"):
    _env = os.environ.get(f"AR_{_v}")
    if _env is not None:
        if _v in ("PARAMS_PATH", "VAL_PARAMS_PATH", "LR_SCHEDULE", "LOSS_FN", "AMP_DTYPE"):
            globals()[_v] = _env
        else:
            globals()[_v] = eval(_env)

# ---------------------------------------------------------------------------
# Validation dataset
# ---------------------------------------------------------------------------

class ValDataset:
    """Load full validation images from one or more directories, apply degradation.

    Returns (degraded, clean) float32 tensors in [0, 1], shape [3, H, W].
    Images are kept at their original resolution for per-image PSNR evaluation.
    """

    def __init__(self, val_dirs, count=0, params_path=None):
        if isinstance(val_dirs, str):
            val_dirs = [val_dirs]
        self.img_paths = []
        for d in val_dirs:
            paths = sorted(scandir(d, full_path=True))
            if count and len(paths) > count:
                paths = paths[:count]
            self.img_paths.extend(paths)
        self.pipeline = load_degradation_params(params_path) if params_path else []
        print(f"ValDataset: {len(self.img_paths)} images from {len(val_dirs)} dir(s)")

    def __len__(self):
        return len(self.img_paths)

    def __getitem__(self, idx):
        img = np.array(Image.open(self.img_paths[idx]).convert("RGB"), dtype=np.uint8)
        clean = img.copy()
        for func_name, severity in self.pipeline:
            img = add_distortion(img, severity=severity, distortion_name=func_name)

        degraded_t = torch.from_numpy(img).permute(2, 0, 1).float() / 255.0
        clean_t = torch.from_numpy(clean).permute(2, 0, 1).float() / 255.0
        return degraded_t, clean_t


RGB_TO_YCRCB = torch.tensor([[0.299, 0.587, 0.114],
                                  [-0.169, -0.331, 0.500],
                                  [0.500, -0.419, -0.081]])

def rgb_to_y(pred, target):
    """PSNR on Y channel (BT.601). Input [B,3,H,W] in [0,1]."""
    w = RGB_TO_YCRCB[0].to(pred.device).view(1, 3, 1, 1)
    return (pred * w).sum(dim=1, keepdim=True), (target * w).sum(dim=1, keepdim=True)

def compute_psnr(pred, target):
    """PSNR in dB. Assumes pixel values in [0, 1]."""
    mse = F.mse_loss(pred, target)
    if mse == 0:
        return 100.0
    return 20 * math.log10(1.0) - 10 * math.log10(mse.item())

def compute_ssim(pred, target):
    """SSIM using skimage on numpy arrays [H,W,C] in uint8 [0,255]."""
    from skimage.metrics import structural_similarity as ssim
    pred_np = (pred.clamp(0, 1) * 255).byte().cpu().numpy().transpose(1, 2, 0)
    target_np = (target.clamp(0, 1) * 255).byte().cpu().numpy().transpose(1, 2, 0)
    return ssim(pred_np, target_np, channel_axis=2, data_range=255)

@torch.no_grad()
def evaluate(model, val_dataset, device, autocast_ctx):
    """Compute PSNR/SSIM in RGB and Y over full validation set.
    Uses eager-mode model (uncompiled) to avoid recompilation for variable image sizes.
    """
    eval_model = getattr(model, '_orig_mod', model)  # uncompiled for variable-size eval
    eval_model.eval()
    metrics = {"psnr_rgb": 0.0, "psnr_y": 0.0, "ssim_rgb": 0.0, "ssim_y": 0.0}
    n = len(val_dataset)
    for i in range(n):
        degraded, clean = val_dataset[i]
        degraded = degraded.unsqueeze(0).to(device)
        clean = clean.unsqueeze(0).to(device)
        with autocast_ctx:
            pred = eval_model(degraded)
        pred_f = pred.float()
        clean_f = clean.float()
        metrics["psnr_rgb"] += compute_psnr(pred_f, clean_f)
        pred_y, clean_y = rgb_to_y(pred_f, clean_f)
        metrics["psnr_y"] += compute_psnr(pred_y, clean_y)
        metrics["ssim_rgb"] += compute_ssim(pred_f[0], clean_f[0])
        metrics["ssim_y"] += compute_ssim(pred_y[0], clean_y[0])
    model.train()
    return {k: v / n for k, v in metrics.items()}

def fmt_metrics(m):
    return (f"PSNR_RGB={m['psnr_rgb']:.2f} PSNR_Y={m['psnr_y']:.2f} "
            f"SSIM_RGB={m['ssim_rgb']:.4f} SSIM_Y={m['ssim_y']:.4f}")


# ---------------------------------------------------------------------------
# Model — simplified SwinIR for image restoration (no upsampling, window SDPA)
# Based on: SwinIR (Liang et al., 2021), modernized with F.scaled_dot_product_attention
# ---------------------------------------------------------------------------

class WindowSDPA(nn.Module):
    """Window-based multi-head attention using F.scaled_dot_product_attention.

    Supports regular (W-MSA) and shifted (SW-MSA) window partitioning.
    Uses PyTorch's native SDPA which dispatches to flash-attention on supported GPUs.
    """

    def __init__(self, dim, num_heads, window_size=8, shift_size=0):
        super().__init__()
        self.dim = dim
        self.num_heads = num_heads
        self.head_dim = dim // num_heads
        self.window_size = window_size
        self.shift_size = shift_size
        self.qkv = nn.Linear(dim, dim * 3, bias=False)
        self.proj = nn.Linear(dim, dim)

    def forward(self, x, x_size):
        B, L, C = x.shape
        H, W = x_size
        ws = self.window_size
        assert H % ws == 0 and W % ws == 0, f"Spatial dims ({H},{W}) must be multiples of window_size {ws}"

        # [B, H*W, C] → [B, H, W, C]
        x = x.view(B, H, W, C)

        # Cyclic shift for SW-MSA
        if self.shift_size > 0:
            x = torch.roll(x, shifts=(-self.shift_size, -self.shift_size), dims=(1, 2))

        # Window partition: [B, H, W, C] → [B*nW, ws*ws, C]
        nH, nW = H // ws, W // ws
        x = x.view(B, nH, ws, nW, ws, C)
        x = x.permute(0, 1, 3, 2, 4, 5).contiguous().view(-1, ws * ws, C)

        # QKV projection → multi-head SDPA
        B_win, N, _ = x.shape
        qkv = self.qkv(x).view(B_win, N, 3, self.num_heads, self.head_dim)
        q, k, v = qkv.unbind(dim=2)
        q, k, v = q.transpose(1, 2), k.transpose(1, 2), v.transpose(1, 2)  # [B_win, nH, N, d]

        x = F.scaled_dot_product_attention(q, k, v)  # flash-attn backend

        # Merge heads: [B_win, nH, N, d] → [B_win, N, C]
        x = x.transpose(1, 2).contiguous().view(B_win, N, C)
        x = self.proj(x)

        # Window reverse: [B*nW, ws*ws, C] → [B, H, W, C]
        x = x.view(B, nH, nW, ws, ws, C)
        x = x.permute(0, 1, 3, 2, 4, 5).contiguous().view(B, H, W, C)

        # Reverse cyclic shift
        if self.shift_size > 0:
            x = torch.roll(x, shifts=(self.shift_size, self.shift_size), dims=(1, 2))

        return x.view(B, L, C)


class SwinBlock(nn.Module):
    """Swin Transformer block: window SDPA + MLP, pre-norm style."""

    def __init__(self, dim, num_heads, window_size=8, shift_size=0, mlp_ratio=2):
        super().__init__()
        self.norm1 = nn.LayerNorm(dim)
        self.attn = WindowSDPA(dim, num_heads, window_size, shift_size)
        self.norm2 = nn.LayerNorm(dim)
        self.mlp = nn.Sequential(
            nn.Linear(dim, int(dim * mlp_ratio)),
            nn.GELU(),
            nn.Linear(int(dim * mlp_ratio), dim),
        )

    def forward(self, x, x_size):
        x = x + self.attn(self.norm1(x), x_size)
        x = x + self.mlp(self.norm2(x))
        return x


class RSTB(nn.Module):
    """Residual Swin Transformer Block: Swin blocks + conv skip connection."""

    def __init__(self, dim, depth, num_heads, window_size=8, mlp_ratio=2):
        super().__init__()
        self.blocks = nn.ModuleList([
            SwinBlock(dim, num_heads, window_size,
                      shift_size=0 if i % 2 == 0 else window_size // 2,
                      mlp_ratio=mlp_ratio)
            for i in range(depth)
        ])
        self.conv = nn.Conv2d(dim, dim, 3, 1, 1)

    def forward(self, x, x_size):
        for blk in self.blocks:
            x = blk(x, x_size)
        B, L, C = x.shape
        H, W = x_size
        feat = x.transpose(1, 2).view(B, C, H, W)
        feat = self.conv(feat).flatten(2).transpose(1, 2)
        return x + feat


class RestoreNet(nn.Module):
    """SwinIR for image restoration (no upsampling, same-resolution in/out).

    Architecture:
      1. Shallow feature extraction: 3×3 conv
      2. Deep feature extraction: RSTB stack (window-based transformer)
      3. Reconstruction: conv → conv with global residual

    Args:
        in_ch: Input/output channels (default 3 for RGB).
        embed_dim: Feature dimension throughout the transformer.
        depths: Number of Swin blocks per RSTB stage.
        num_heads: Attention heads per stage.
        window_size: Window size for W-MSA / SW-MSA (spatial dims must be multiples).
        mlp_ratio: MLP hidden dimension ratio.
    """

    def __init__(self, in_ch=3, embed_dim=64, depths=(2, 2, 2, 2),
                 num_heads=(4, 4, 4, 4), window_size=8, mlp_ratio=2):
        super().__init__()
        self.window_size = window_size
        self.embed_dim = embed_dim

        # Shallow feature extraction
        self.conv_first = nn.Conv2d(in_ch, embed_dim, 3, 1, 1)

        # Deep feature extraction: RSTB stack
        self.layers = nn.ModuleList([
            RSTB(embed_dim, d, nh, window_size, mlp_ratio)
            for d, nh in zip(depths, num_heads)
        ])
        self.norm = nn.LayerNorm(embed_dim)

        # Reconstruction
        self.conv_after_body = nn.Conv2d(embed_dim, embed_dim, 3, 1, 1)
        self.conv_last = nn.Conv2d(embed_dim, in_ch, 3, 1, 1)

    def _pad_to_window(self, x):
        _, _, H, W = x.shape
        ws = self.window_size
        pad_h = (ws - H % ws) % ws
        pad_w = (ws - W % ws) % ws
        if pad_h or pad_w:
            x = F.pad(x, (0, pad_w, 0, pad_h), mode='reflect')
        return x

    def forward(self, x):
        H_in, W_in = x.shape[2:]
        x = self._pad_to_window(x)

        # Shallow feature
        feat = self.conv_first(x)                     # [B, C, H, W]
        B, C, H, W = feat.shape

        # Patch embed: [B, C, H, W] → [B, H*W, C]
        x_seq = feat.flatten(2).transpose(1, 2)

        # RSTB stack
        for layer in self.layers:
            x_seq = layer(x_seq, (H, W))

        # Patch unembed: [B, H*W, C] → [B, C, H, W]
        x_seq = self.norm(x_seq)
        feat = x_seq.transpose(1, 2).view(B, C, H, W)

        # Reconstruction with skip connections
        out = self.conv_after_body(feat) + self.conv_first(x)
        out = self.conv_last(out) + x[:, :3, :, :]    # global residual

        return out[:, :, :H_in, :W_in]


# ---------------------------------------------------------------------------
# Setup
# ---------------------------------------------------------------------------

t_start = time.time()
torch.manual_seed(42)
torch.cuda.manual_seed(42)
torch.set_float32_matmul_precision("high")
device = torch.device("cuda")
amp_dtype = torch.bfloat16 if AMP_DTYPE == "bfloat16" else torch.float32
autocast_ctx = torch.amp.autocast(device_type="cuda", dtype=amp_dtype)
print(f"AMP dtype: {AMP_DTYPE}")

print(f"Device: {torch.cuda.get_device_name(device)}")
print(f"Params: {PARAMS_PATH}")
print(f"Train shards: {TRAIN_SHARDS}")
print(f"Val dirs: {len(VAL_DIRS)} sets, {VAL_COUNT if VAL_COUNT else 'all'} images each")

# Build validation dataset (full images, evaluated one at a time)
val_dataset = ValDataset(VAL_DIRS, count=VAL_COUNT, params_path=VAL_PARAMS_PATH)
val_x, val_y = val_dataset[0]
print(f"Val: {len(val_dataset)} images, example shape {tuple(val_x.shape)}")

# Model
model = RestoreNet(in_ch=3, embed_dim=EMBED_DIM, depths=DEPTHS,
                    num_heads=NUM_HEADS, window_size=WINDOW_SIZE, mlp_ratio=MLP_RATIO)
model.to(device)
num_params = sum(p.numel() for p in model.parameters())
print(f"Model params: {num_params:,}")

model = torch.compile(model, dynamic=False)

# Optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=LEARNING_RATE,
                               betas=ADAM_BETAS, weight_decay=WEIGHT_DECAY)

# Training dataloader
train_loader = make_dataloader_restoration(
    params_path=PARAMS_PATH,
    shards_url=TRAIN_SHARDS,
    batch_size=BATCH_SIZE,
    num_workers=NUM_WORKERS,
    shuffle_buffer=SHUFFLE_BUFFER,
)
x, y, epoch = next(train_loader)
x, y = x.to(device), y.to(device)

print(f"Train: x {tuple(x.shape)} [{x.min():.3f},{x.max():.3f}], "
      f"y {tuple(y.shape)} [{y.min():.3f},{y.max():.3f}]")
# Training regime
TOTAL_PATCHES = 120765
STEPS_PER_EPOCH = TOTAL_PATCHES // BATCH_SIZE  # 7548
if EPOCH_BUDGET > 0:
    MAX_STEPS = EPOCH_BUDGET * STEPS_PER_EPOCH
    VAL_INTERVAL = max(1, MAX_STEPS // CHECKPOINT_INTERVAL)
    USE_TIME_BUDGET = False
else:
    MAX_STEPS = 10 ** 9
    VAL_INTERVAL = 10 ** 9
    USE_TIME_BUDGET = True

print(f"Regime: {'time_budget='+str(TIME_BUDGET)+'s' if USE_TIME_BUDGET else 'epoch_budget='+str(EPOCH_BUDGET)+' ('+str(MAX_STEPS)+' steps)'}")
print(f"Checkpoints: {CHECKPOINT_INTERVAL} per epoch, VAL_INTERVAL={VAL_INTERVAL}")
print(f"Batch: {BATCH_SIZE}  LR: {LEARNING_RATE}  Loss: {LOSS_FN}  Clip: {GRAD_CLIP}")

# ---------------------------------------------------------------------------
# Loss helpers
# ---------------------------------------------------------------------------

def _sobel_kernels():
    """Return (kx, ky) Sobel kernels [1, 1, 3, 3]."""
    kx = torch.tensor([[-1., 0., 1.], [-2., 0., 2.], [-1., 0., 1.]]) / 4.
    ky = torch.tensor([[-1., -2., -1.], [0., 0., 0.], [1., 2., 1.]]) / 4.
    return kx.view(1, 1, 3, 3), ky.view(1, 1, 3, 3)

def edge_loss(pred, target):
    """Sobel edge-aware loss (L1 on gradient magnitude difference)."""
    kx, ky = _sobel_kernels()
    kx, ky = kx.to(pred.device), ky.to(pred.device)
    gx_p = F.conv2d(pred, kx, padding=1)
    gy_p = F.conv2d(pred, ky, padding=1)
    gx_t = F.conv2d(target, kx, padding=1)
    gy_t = F.conv2d(target, ky, padding=1)
    mag_p = torch.sqrt(gx_p ** 2 + gy_p ** 2 + 1e-6)
    mag_t = torch.sqrt(gx_t ** 2 + gy_t ** 2 + 1e-6)
    return F.l1_loss(mag_p, mag_t)

def fft_loss(pred, target):
    """Frequency-domain L1 loss on magnitude spectrum."""
    pred_f = torch.fft.rfft2(pred.float(), norm='ortho')
    target_f = torch.fft.rfft2(target.float(), norm='ortho')
    return F.l1_loss(pred_f.abs(), target_f.abs())

def compute_loss(pred, target):
    """Flexible loss dispatch based on LOSS_FN."""
    if LOSS_FN == "l1":
        return F.l1_loss(pred, target)
    if LOSS_FN == "mse":
        return F.mse_loss(pred, target)
    if LOSS_FN == "huber":
        return F.huber_loss(pred, target, delta=HUBER_DELTA)
    if LOSS_FN == "l1+mse":
        w1, w2 = LOSS_WEIGHTS
        return w1 * F.l1_loss(pred, target) + w2 * F.mse_loss(pred, target)
    if LOSS_FN == "l1+fft":
        w1, w2 = LOSS_WEIGHTS
        return w1 * F.l1_loss(pred, target) + w2 * fft_loss(pred, target)
    if LOSS_FN == "l1+edge":
        w1, w2 = LOSS_WEIGHTS
        return w1 * F.l1_loss(pred, target) + w2 * edge_loss(pred, target)
    return F.l1_loss(pred, target)

# ---------------------------------------------------------------------------
# LR schedule
# ---------------------------------------------------------------------------

def get_lr_multiplier(step, total_steps):
    if step < WARMUP_STEPS:
        return step / max(1, WARMUP_STEPS)
    if LR_SCHEDULE == "cosine":
        progress = (step - WARMUP_STEPS) / max(1, total_steps - WARMUP_STEPS)
        return 0.5 * (1 + math.cos(math.pi * progress))
    return 1.0

# ---------------------------------------------------------------------------
# Training loop
# ---------------------------------------------------------------------------

t_start_training = time.time()
smooth_loss = 0
total_training_time = 0
step = 0
best_train_psnr = 0
best_checkpoint = {"step": 0, "metrics": None}
checkpoint_steps = set(range(VAL_INTERVAL, MAX_STEPS + 1, VAL_INTERVAL))

while True:
    torch.cuda.synchronize()
    t0 = time.time()

    # Forward + backward
    with autocast_ctx:
        pred = model(x)
        loss = compute_loss(pred, y)

    loss.backward()

    if GRAD_CLIP > 0:
        torch.nn.utils.clip_grad_norm_(model.parameters(), GRAD_CLIP)

    # LR update
    lrm = get_lr_multiplier(step, MAX_STEPS)
    for group in optimizer.param_groups:
        group["lr"] = LEARNING_RATE * lrm

    optimizer.step()
    optimizer.zero_grad(set_to_none=True)

    # Fetch next batch
    x, y, epoch = next(train_loader)
    x, y = x.to(device, non_blocking=True), y.to(device, non_blocking=True)

    torch.cuda.synchronize()
    t1 = time.time()
    dt = t1 - t0

    # Skip warmup steps for timing
    if step > 5:
        total_training_time += dt

    # Logging
    loss_f = loss.item()
    ema_beta = 0.95
    smooth_loss = ema_beta * smooth_loss + (1 - ema_beta) * loss_f
    debiased_loss = smooth_loss / (1 - ema_beta ** (step + 1))

    if step % LOG_INTERVAL == 0:
        with torch.no_grad(), autocast_ctx:
            train_psnr = compute_psnr(pred.float(), y)
            best_train_psnr = max(best_train_psnr, train_psnr)

    # Checkpoint: save model + run full validation
    if step > 0 and step in checkpoint_steps:
        ckpt_file = f"ckpt_step{step}.pt"
        torch.save({"step": step, "model": model.state_dict(), "optimizer": optimizer.state_dict()}, ckpt_file)
        m = evaluate(model, val_dataset, device, autocast_ctx)
        print(f"\n  [Ckpt @ step {step}/{MAX_STEPS}] {fmt_metrics(m)}")
        if best_checkpoint["metrics"] is None or m["psnr_rgb"] > best_checkpoint["metrics"]["psnr_rgb"]:
            best_checkpoint = {"step": step, "metrics": m}

    if USE_TIME_BUDGET:
        progress = min(total_training_time / TIME_BUDGET, 1.0)
    else:
        progress = min(step / MAX_STEPS, 1.0)
    pct = 100 * progress
    imgs_per_sec = int(BATCH_SIZE / dt) if dt > 0 else 0

    print(f"\rstep {step:05d}/{MAX_STEPS} ({pct:.1f}%) | loss: {debiased_loss:.6f} | "
          f"lr: {LEARNING_RATE * lrm:.2e} | dt: {dt*1000:.0f}ms | imgs/s: {imgs_per_sec} | "
          f"epoch: {epoch}    ", end="", flush=True)

    # GC management
    if step == 0:
        gc.collect()
        gc.freeze()
        gc.disable()
    elif (step + 1) % 5000 == 0:
        gc.collect()

    step += 1

    if USE_TIME_BUDGET:
        if step > 10 and total_training_time >= TIME_BUDGET:
            break
    else:
        if step >= MAX_STEPS:
            break

print()

# ---------------------------------------------------------------------------
# Final evaluation (if not already done at last checkpoint)
# ---------------------------------------------------------------------------

if best_checkpoint["metrics"] is None:
    print("Running final validation...")
    m = evaluate(model, val_dataset, device, autocast_ctx)
    best_checkpoint = {"step": step, "metrics": m}

# Load best checkpoint for final metrics
ckpt_file = f"ckpt_step{best_checkpoint['step']}.pt"
if os.path.exists(ckpt_file):
    ckpt = torch.load(ckpt_file, map_location=device, weights_only=True)
    model.load_state_dict(ckpt["model"])
    print(f"\nLoaded best checkpoint: step {best_checkpoint['step']}")

# Final eval with best model
final_metrics = evaluate(model, val_dataset, device, autocast_ctx)
total_imgs = step * BATCH_SIZE

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------

t_end = time.time()
peak_vram_mb = torch.cuda.max_memory_allocated() / 1024 / 1024
print("---")
print(f"best_step:         {best_checkpoint['step']}")
print(f"psnr_rgb:          {final_metrics['psnr_rgb']:.2f}")
print(f"psnr_y:            {final_metrics['psnr_y']:.2f}")
print(f"ssim_rgb:          {final_metrics['ssim_rgb']:.4f}")
print(f"ssim_y:            {final_metrics['ssim_y']:.4f}")
print(f"best_train_psnr:   {best_train_psnr:.2f}")
print(f"final_loss:        {loss.item():.6f}")
print(f"training_seconds:  {total_training_time:.1f}")
print(f"total_seconds:     {t_end - t_start:.1f}")
print(f"peak_vram_mb:      {peak_vram_mb:.1f}")
print(f"num_steps:         {step}")
print(f"num_params_M:      {num_params / 1e6:.1f}")
print(f"total_imgs:        {total_imgs}")
print(f"batch_size:        {BATCH_SIZE}")
print(f"learning_rate:     {LEARNING_RATE}")
print(f"val_psnr_db:       {final_metrics['psnr_rgb']:.2f}")
